name: readsms
description: A flutter plugin that reads incoming SMS on device as a broadcast stream.
version: 0.2.0+4
homepage: "https://github.com/Ayush783/readsms_plugin"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ayush783.readsms
        pluginClass: ReadsmsPlugin

